---
- name: Installation Nginx and MariaDB
  hosts: Installation-web-db
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install MariaDB
      apt:
        name: mariadb
        state: present
